# Generated by Django 4.0.5 on 2022-08-18 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datepicker',
            field=models.DateField(default=datetime.date(2022, 8, 18)),
        ),
    ]
